Config = {
  tipgaraje = {
    [1] = {
      tipGaraj = "~b~Politie",
      marker = {0, 102, 255},
      masini = {
        {"polbmw","radio.police","BMW M3 Rutiera"},
        {"polgolf","radio.police","VW GOLF"},
        {"passatpolitie","radio.police","VW Passat Rutiera"},
        {"polgs350","radio.police","Lexus Rutiera"},
        {"police3","radio.police","Logan Rutiera"},
        {"polopolitie","radio.police","Polo Rutiera"},
        {"policeb","radio.police","Motor Rutiera"},
        {"vitofreecosmacreppdro","radio.police","Duba Mercedes Vito Politie"},
        {"dubapol","radio.police","Duba VW"},
        --{"m5pol","radio.police","BMW M5 Rutiera"},
        {"polduster","radio.police","Duster Rutiera"},
        {"subarupol","radio.police","Subaru Rutiera"},
        {"skodapol","radio.police","Skoda Rutiera"},
        {"a6um","radio.police","Audi A6 Undercover"},
        {"mp2","radio.police","Ford Duba"},
        {"umarteon","radio.police","Unmarked VW Arteon"},
        {"umcharger","radio.police","Unmarked Charger"},
        {"viper","radio.police","Unmarked Viper"},
        {"viper2","radio.police","Unmarked Viper2"},
        {"pd_avent","radio.police","Unmarked lambo"},
        {"17raptorpd","radio.police","17raptorpd"},
        {"insurgentsias","radio.police","insurgentsias"},
        {"machito1","radio.police","machito1"},
        {"opelpolitie","radio.police","opelpolitie"},
        {"pol718","radio.police","pol718"},
        {"polcayenne","radio.police","polcayenne"},
        {"polchiron","radio.police","polchiron"},
        {"polduster","radio.police","polduster"},
        {"polgs350","radio.police","polgs350"},
        {"police2","radio.police","police2"},
        {"police4","radio.police","police4"},
        {"policeb","radio.police","policeb"},
        {"sheriff2","radio.police","sheriff2"},
        {"skodabreckpolitie","radio.police","skodabr"},
        {"skodapolitie","radio.police","skodap"},
        {"x5unmarked","radio.police","x5unmarked"},
        {"wmfenyrcop","radio.police","Fenyr"},
        {"riot","radio.police","Riot"},
        {"emperor2","radio.police","Scoala"},
        {"umvolvo","radio.police","Volvo Unmarked"}
      }
    },
    [2] = {
      tipGaraj = "~r~UPU-SMURD",
      marker ={ 255, 51, 0},
      masini = {
        {"ambulance","emergency.market","Ambulanta SMURD"},
        {"ambulancei","emergency.market","Ambulanta1 SMURD"},
        {"corvettepd","emergency.market","corvet SMURD"},
        {"nissanpp3","emergency.market","nissan SMURD"},
        {"qrv","emergency.market","grv SMURD"},
        {"raems","emergency.market","rea SMURD"},
        {"smeker","emergency.market","smeker SMURD"},
        {"smurdcrep5","emergency.market","creap SMURD"},
        {"sprintersmurd","emergency.market","Sprinter SMURD"},
        {"renaultsmurd","emergency.market","Renault SMURD"},
        {"ml63smurd","emergency.market","Mercedes-Benz ML63 SMURD"},
        --{"firetruk","emergency.market","Masina Pompieri"},
        {"audiq8","emergency.market","Audi Q8 SMURD"}
        --{"x5smurd","emergency.market","BMW x5"}

      }
    },
    [3] = {
      tipGaraj = "~p~Mafie",
      marker ={ 96, 0, 128},
      masini = {
        --La Famiglia
       --[[{"bmm","familia.masini","Bentley"}, FOLOSIT
        {"cesc21","familial.masini","Cadilac"}, FOLOSIT
        {"cls2015","familia.masini","Mercedes CLS 2016"}, FOLOSIT
        {"rculi","familia.masini","Rollce Royce Culinan"}, FOLOSIT
        {"panamera18","familia.masini","Porsche Panamera"}, FOLOSIT
        -- PEPSY
        {"g65","pepsy.masini","Mercedes G65"}, FOLOSIT LA CIVILI
        {"bentayga17","pepsy.masini","Bentley Bentayga"}, LA CIVILI
        {"wraith","pepsy.masini","Rolls Royce Avarus"}, LA CIVILI
        -- GEO ]]
        --{"e63s","yakuza.masini","Mercedes E63 S"}, FOLOSIT
        --{"panamera18","yakuza.masini","Porsche Panamera"}, FOLOSIT
        --Curcubeu
        --{"rs5r","curcubeu.masini","AUDI RS5 "}, FOLOSIT
        --{"x6m","curcubeu.masini","BMW X6m"}, FOLOSIT sinaloa
        --{"amggtrr20","curcubeu.masini","Mercedes-Benz AMG GT-R"}, FOLOSIT
        --Buccaneer
        --{"buccaneer","scu.masini","Buccaneer Custom"}, LIBER
        --{"tornado2","scu.masini","Tornado2"}, LIBER
        {"tulenis","sinaloa.masini","Dukes"},   --sinaloa
        {"f350offroadspec","sinaloa.masini","Dukes 2"},  --sinaloa
        {"dukes","sinaloa.masini","Dukes 3"},    --sinaloa
        {"dbx","sinaloa.masini","Aston Martin DBX"},   --sinaloa
        {"faction2","crips.masini","Faction2"},
        --{"gauntlet3","scu.masini","Gauntlet 3"}, LIBER      
        {"moonbeam2","crips.masini","Moonbeam 2"},
        --{"voodoo","scu.masini","Voodoo"}, LIBER 
        {"Mb400","cosa.masini","Mercedes-Benz EQC400"}, 
        {"bentayga17","narcos.masini","Bentley Bentayga"}, 
        {"wraith","narcos.masini","Rolls Royce Avarus"},
        {"19S650","narcos.masini","Maybach Narcos"},
        {"g63amg6x6","narcos.masini","Mercedes G64 AMG 6x6"},
        {"poltaxi","narcos.masina","Masina UnderCover"},
        {"poltaxi","sindicat.masina","Masina UnderCover"},
        {"poltaxi","vagos.masina","Masina UnderCover"},
        {"poltaxi","crips.masina","Masina UnderCover"},
        {"poltaxi","sinaloa.masina","Masina UnderCover"},
        {"poltaxi","scu.masina","Masina UnderCover"},
        --{"agerarsc","narcos.masini","Koenisegg Agera"},
        {"baller6","sindicat.masini","Range Rover Blindat"},
        {"contender","sindicat.masini","SUV Blindat"},
        {"cog552","sindicat.masini","Bentlay Blindat"},
        {"kuruma2","sindicat.masini","Kuruma Blindat"},
        {"schafter6","sindicat.masini","Mercedes Blindat"},
        {"rs5r","vagos.masini","Audi RS5"},
        {"e63s","vagos.masini","Mercedes E63 S"},
        {"bmm","scu.masini","Bentley"},
        {"cesc21","scu.masini","Cadilac"},
        {"q820","scu.masini","Audi Q8 2020"},
        {"cls2015","scu.masini","Mercedes CLS 2016"},        
        {"amggtrr20","vagos.masini","Mercedes-Benz AMG GT-R"},
        {"XPERIA38","vagos.masini","Mercedes-Benz AMG G63"},
        {"rculi","scu.masini","Rollce Royce Culinan"},
        {"panamera18","scu.masini","Porsche Panamera"}
      }
    },
    [4] = {
      tipGaraj = "~y~VIP",
      marker = {230, 230, 0},
      masini = {
        -- VIP 4

        {"regera","vip4.masini","Koenisegg Regera VIP4"},
        {"p1","vip4.masini","McLaren P1 VIP4"},
        {"sian","vip4.masini","Lamborghini Sian VIP4"},
        {"b2pro","vip4.masini","Marussia B2 VIP4"},
        {"bolide","vip4.masini","Bugatti Bolide VIP4"},
        {"rrghost21","vip4.masini","Rolls Royce Ghost VIP4"},

        -- VIP 3 
        
        {"teslax","vip3.masini","Tesla X VIP3"},
        {"mi8","vip3.masini","BMW M8 VIP3"},
        {"demonhawk","vip3.masini","Jeep DemonHawk VIP3"},
        {"720s","vip3.masini","McLaren 720s VIP3"},

        -- VIP 2

        {"lp770","vip2.masini","Lamborghini Centenario 770 VIP2"},
        {"x5m","vip2.masini","BMW X5m VIP2"},
        --{"moslersupergt","vip2.masini","Mosler Super GT VIP2"},


        -- VIP 1
        {"17m760i","vip1.masini","BMW760i 2017 VIP1"},
        {"RS72020","vip1.masini","AUDI RS7 2020 VIP1 "}
      }
    },
    [5] = {
      tipGaraj = "~g~Jucatori",
      marker = {102, 255, 51},
      masini = {
        {"2004astra","user.salariu","Opel Astra J"},
        {"ap2","user.salariu","Honda S2000 AP2"},
        {"asea","user.salariu","VW Jetta 1998"},
        {"asterope","user.salariu","Dacia Logan 2004"},
        {"bmwe38","user.salariu","BMW Seria 7 e38"},
        {"civic","user.salariu","Honda Civic 2000"},
        {"corsa05","user.salariu","Opel Corsa 2005"},
        {"daduster","user.salariu","Dacia Duster"},
        {"ds4","user.salariu","Citroen DS4"},
      --  {"fd","user.salariu","Mazda RX-7 Older"},
        {"golfgti","user.salariu","VW Golf 5 GTI"},
        {"logan","user.salariu","Dacia Logan 2007"},
        {"NA6","user.salariu","Mazda Miata MX-5"},
        {"polo2018","user.salariu","Volkswagen Polo 2018"},
        {"s600w220","user.salariu","Mercedes s600 W220"},
        {"sandero","user.salariu","Dacia Sandero"},
        {"sandero08","user.salariu","Dacia Sandero 08"},
        {"subwrx","user.salariu","Subaru WRX"},
        {"tico","user.salariu","Tico"},
        --{"v242","user.salariu","Volvo V242"},
        {"volvo850r","user.salariu","Volvo 850 R"},
        {"x5e53","user.salariu","BMW x5 E53"},
        {"a8fsi","user.salariu","Audi A8 2011"},
        {"contgt13","user.salariu","Bentley Continental 2013"},
        {"dzsb","user.salariu","Rollce Royce Phantom"},
        {"intunder","user.salariu","Lincoln Continental"},
        {"passat","user.salariu","Volkswagen Passat B8"},
        {"s500w222","user.salariu","Mercedes S500 W222"},
        {"xfr","user.salariu","Jaguar XFR"},
        {"a8audi","user.salariu","Audi A8 2008"},
        {"bmwe65","user.salariu","BMW Seria 7 e65 2006"},
        {"camry18","user.salariu","Toyota Camry 2018"},
        {"charger","user.salariu","Dodge Charger 2014"},
        {"exemplar","user.salariu","Hyundai Elantra"},
        {"felon","user.salariu","Chrysler Genesis G80"},
        {"ibiza","user.salariu","Seat Ibiza"},
        {"ody18","user.salariu","Honda Odyssey 2019"},
        {"pacev","user.salariu","Renault Escape 2019"},
        {"passatr","user.salariu","Volkswagen Passat B8 Break"},
        {"s60pole","user.salariu","Volvo S60"},
        {"schafter6","user.salariu","Infinity q50"},
        {"tailgater","user.salariu","Ford Taurus"},
        {"tmodel","user.salariu","Tesla Model 3"},
        {"v60","user.salariu","Volvo V60"},
        {"69charger","user.salariu","Dodge Charger 69"},
        {"belair","user.salariu","Chevy' Belair"},
        {"buccaneer","user.salariu","Chevrolet Impala OLD SCHOOL"},
        {"c10","user.salariu","Chevy' c10"},
        {"casco","user.salariu","Ford Hot Rod"},
        {"eleanor","user.salariu","Ford Mustang GT500 Shelby 1967"},
        {"emperor","user.salariu","Ford Crown Victoria 1980"},
        {"fordh","user.salariu","Ford Mustang Hoonigan"},
        {"fugitive","user.salariu","Lada"},
        {"infernus","user.salariu","Ferrari Testarossa"},
        {"mbw111","user.salariu","Mercedes Benz S220 w111"},
        {"mgb","user.salariu","MGB GT"},
        {"Nova","user.salariu","Chevrolet Nova"},
        {"pstan48","user.salariu","Packard"},
        {"rx3","user.salariu","Mazda RX3"},
        {"tbird","user.salariu","Ford Thunderbird"},
        {"turbo33","user.salariu","Porsche turbo 930"},
        {"vigero","user.salariu","Dodge Challanger"},
        {"18velar","user.salariu","Range Rover Velar"},
        {"amarok","user.salariu","VW Amarok"},
        {"bjxl","user.salariu","Kia Sportage"},
        {"Cavalcade2","user.salariu","Audi q7"},
        {"cayenne","user.salariu","Porsche Cayenne"},
        {"fpacehm","user.salariu","Jaguar F Pace SVR"},
        {"FX50s","user.salariu","Infinity FX50s"},
        {"gmcs","user.salariu","GMC Sierra 1500"},
        {"gmcyd","user.salariu","GMC Yukon Denali"},
        {"gmt900escalade","user.salariu","Cadilac Escalade"},
        {"jeep2012","user.salariu","Jeep 2012"},
        {"jeepreneg","user.salariu","Jeep Renegade"},
        {"levante","user.salariu","Maserati Levante"},
        {"navigator","user.salariu","Lincoln Navigator"},
        {"patriot","user.salariu","Hummer H1"},
        {"q30","user.salariu","Infiniti q30"},
        {"quashqai16","user.salariu","Nissan Quashqa"},
        {"rrst","user.salariu","Range Rover Sport"},
        {"santafe","user.salariu","Hyundai SantaFe"},
        {"srt8","user.salariu","Jeep SRT8"},
        {"stelvio","user.salariu","Alfa Romeo Stelvio"},
        {"titan17","user.salariu","Nissan Titan"},
        {"trailcat","user.salariu","Jeep Trailcat"},
        {"trhawk","user.salariu","Jeep Grand Cherokee S"},
        {"x6m","user.salariu","BMW x6 M"},
        {"jukonxl","user.salariu","GMC Yukon X"},
        {"kangoo","user.salariu","Renault Kangoo"},
        {"v250","user.salariu","Mercedes V250"},
        {"yukonxl","user.salariu","GMC"},
                --pana la vans
        {"4c","user.salariu","Alfa Romeo 4C"},
        {"180sx","user.salariu","Nissan 180SX"},
        {"370z","user.salariu","Nissan 370z"},
        {"a45amg","user.salariu","Mercedes A45 AMG"},
        {"acr","user.salariu","Dodge Viper acr"},
        {"aqv","user.salariu","Alfa Romeo Giulia"},
        {"audirs6tk","user.salariu","Audi RS6 TK"},
        {"audis8om","user.salariu","Audi S8"},
        {"ben17","user.salariu","Bentley Continental GT"},
        {"bmwm8","user.salariu","BMW M8"},
        {"brz","user.salariu","Subaru BRZ"},
        {"brzbn","user.salariu","Subaru BRZ v2"},
        {"c7","user.salariu","Chevrolet Corvette (C7)"},
        {"c8","user.salariu","Chevrolet Corvette (C8)"},
        {"CATS","user.salariu","Cadilac CTS-V"},
        {"cx75","user.salariu","Jaguar CX 75"},
        {"e60","user.salariu","BMW M5 E60"},
        {"evo9","user.salariu","MITSUBISHI LANCER EVO 9"},
        {"f82","user.salariu","BMW M4 F82"},
        {"f620","user.salariu","Maserati GranTurismo"},
        {"f824slw","user.salariu","BMW M4 F82 SLW"},
        {"FC3S","user.salariu","Mazda RX-7 FC3S"},
        {"furoregt","user.salariu","Jaguar XKR-S GT"},
        {"hondacivictr","user.salariu","Honda Type R"},
        {"jackal","user.salariu","Kia Stinger 2020"},
        {"lc500","user.salariu","Lexus LC500"},
        {"m2","user.salariu","BMW M2"},
        {"m3","user.salariu","BMW M3"},
        {"m6f13","user.salariu","BMW M6 F13"},
        {"mb18","user.salariu","Mercedes Benz S63 AMG Cabrio"},
        {"mgrantur2010","user.salariu","Maserati  GranTurismo  2010"},
        {"miniroads","user.salariu","Mini Couper Roadester"},
        {"models","user.salariu","Tesla Model S"},
        {"p90d","user.salariu","Tesla Model P90 D"},
        {"moss","user.salariu","Mercedes Benz SLR"},
        {"mustang19","user.salariu","Ford Mustang 19"},
        {"rcf","user.salariu","Lexus RC F"},
        {"rs6","user.salariu","Audi RS 6"},
        {"rs6tk","user.salariu","Audi RS 6 TK"},
        {"rs7","user.salariu","Audi RS 7"},
        {"rs318","user.salariu","Audi RS 3 2018"},
        {"rx8r","user.salariu","Mazda RX8 R"},
        {"s5","user.salariu","Audi S5"},
        {"skyline","user.salariu","Nissan Skyline"},
        {"supra2","user.salariu","Toyota Supra"},
        {"supraa90","user.salariu","Toyota Supra 2019"},
        {"teslapd","user.salariu","Tesla PD-S1000"},
        {"viper","user.salariu","Dodge Viper"},
        {"z4bmw","user.salariu","BMW Z4"},
        {"zl12017","user.salariu","Chevrolet Camaro 2017"},
        {"2019chiron","user.salariu","Bugatti Chiron"},
        {"amv19","user.salariu","Aston Martin Vantage 2019"},
        {"arv10","user.salariu","Audi R8 V10"},
        {"ast","user.salariu","Aston Martin Vanquish DB9"},
        {"comet2","user.salariu","Porsche 718 Cayman S"},
        {"db9v","user.salariu","Aston Martin DB9V Cabrio"},
        {"f430s","user.salariu","Ferrari F430 S"},
        {"f812","user.salariu","Ferrari F812"},
        {"fct","user.salariu","Ferrari Califronia"},
        {"filthynsx","user.salariu","Acura NSX"},
        {"gto","user.salariu","Ferrari GTO"},
        {"gtr","user.salariu","Nissan GTR"},
        {"i8","user.salariu","BMW I8"},
        {"lhuracan","user.salariu","Lamborghini Huracan"},
        {"mp412c","user.salariu","McLaren MP4 12C"},
        {"p911r","user.salariu","Porsche 911r"},
        {"r8ppi","user.salariu","Audi R8 PPI"},
        {"senna","user.salariu","McLaren Senna"},
        {"spyker","user.salariu","Spyker C8"},
        {"tr22","user.salariu","Tesla Roadster"},
        {"r1","user.salariu","Yamaha R1"},
        {"blazer6","user.salariu","ATV"},
        {"bmws","user.salariu","BMW S1000"},
        {"desmo","user.salariu","Ducatti Desmo"},
        {"exciter","user.salariu","Yamaha Exciter"},
        {"brabuse700","botzo.masina","Masina Botzo"},
        {"urus", "hades.masina", "Masina Hades#1"},
        {"develSix", "hades.masina", "Masina Hades#2"},
        {"exc250sm", "hades.masina", "Motor Hades"},
        {"bmwe39", "vito.masina", "Masina Mircea"},
        {"demon", "vito.masina", "Masina Corleone#2"},
        {"silvia", "orlando.masina", "Masina Urechiuse"},             
        {"oracle", "seba.masina", "Masina Seba"},
        {"q820", "seba.masina", "Masina Seba#2"},
        {"1310s", "test.masina", "Masina BotzoT"},
        {"poltaxi","test.masina","Masina UnderCover Botzo"},
        {"g65", "marchi.masina", "Mercedes G65 # MkD"},
        {"bentayga17", "marchi.masina", "Bentley Bentayga # MkD"}, 
        {"wraith", "marchi.masina", "Rolls Royce Wraith # MkD"},
        {"e63s", "marchi.masina", "Mercedes E63 # MkD"}, 
        {"dubsta", "marchi.masina", "Dubsta # MkD"}, 
        {"R50", "alexander.masina", "Masina Alexander"},
        {"rs6c8", "dallas.masina", "Rs6 ~ Dallas"},
        {"bdivo","dallas.masina","Bugatti Divo Dallas#2"},
        {"lamboavj", "dallas.masina","Lamborghini Dallas"},
        {"18performante","dallas.masina","Lamborghini Performante Dallas"},
        {"gt63s", "dallas.masina","Mercedes Benz GT63S Dallas"},
        {"sanctus", "dallas.masina","Motoreta Dallas"},
        {"aperta","test.masina","Masina Personala ~ Ary"},
        {"20x5m","marchi.masina","BMW X5 2020 # MKD"},
        {"windsor2","marchi.masina","Masina Windsor # MKD"},
        {"hermes","marchi.masina","Masina Hermes # MKD"},
        {"sultanrsv8","titel.masina","Masina Personala # Titel"},
        {"mache","remus.masina","Masina Personala # Remus"},
        {"19raptor","remus.masina","Masina Personala # Remus Raptor"},
        {"bug300ss","flocea.masina","Masina Personala # Flocea bug"},
        {"chino2","flocea.masina","Masina Personala # Flocea1"},
        {"zentorno","flg.vehicle","Masina Personala ~ Alex Flg"},
        {"Y1700MAX","zavy.masina","Masina Personala ~ Zavy"}, 
        {"flhxs_streetglide_special18","soa.masina","Motoreta Zavy1"},
        {"slsamg","cris.masina","Motoreta chris"},
        {"ccx","alexene.masina","Motoreta alexene"},          
        {"superd","spike.masina","Masina Spike"}
      }
    },
    [6] = {
      tipGaraj = "~g~Factiune",
      marker = {102, 255, 51},
      masini = {
        {"sultanrs","mofo.vehicle","Sultan RS"},
        {"taxi","taxi.vehicle","Taxi"},
        {"minivan","fan.vehicle","Masina Fan Courier"},
        {"18phantom","garajhitman.acces","Rolls Royce Hitman #1"},
        {"20x5m","garajhitman.acces","BMW X5m Hitman #2"},
        {"rrab","garajhitman.acces","Range Rover Hitman #3"},
        {"gemera","garajhitman.acces","Gemera Hitman #4"},
        {"boxville","hotdecase.acces","Duba #1"},
        {"boxville2","hotdecase.acces","Duba #2"},
        {"flatbed","mecanic.acces","Remorcarii #2"},
        {"boxville3","hotdecase.acces","Duba #3"},
        {"boxville4","hotdecase.acces","Duba #4"},
        {"dinghy","pescar.acces","Barca Pescar"},
        {"hauler","tirist.vehicle","Scania TRUCK"}        
      }
    },
    [7] = {
      tipGaraj = "~g~Elicopter",
      marker = {102, 255, 51},
      masini = {
        {"frogger","vagos.masini","Elicopter LosVagos"},
        {"polmav","radio.police","Elicopter {Politie}"},
        {"haitun","sinaloa.masini","Sinaloa"},
        {"supervolito","emergency.market","supervolito Urgente SMURD"},
        --{"lguardmav","emergency.market","lguardmav Urgente SMURD"},
        --{"smurdelicopter","emergency.market","Elicopter Urgente SMURD"},
        {"valkyrie","narcos.masini","Elicopter Narcos"}  
        --[[{"taxi","taxi.vehicle","Taxi"},
        {"minivan","fan.vehicle","Masina Fan Courier"},
        {"hauler","tirist.vehicle","Scania TRUCK"}]]
      }
  }
 }
}