
	local cfg = {}


	cfg.groups = {
-- SISTEME
		["wanted"] = {

		},
				
		["afacerist"] = {
		
		},	
		["jailer"] = {
		
		},
		["jaile2"] = {
		
		},
		["spargator"] = {		
		},

		["esk"] = {
		},

		["ems"] = {
		"ems.whitelisted"
		},

		["cop"] = {
		"cop.whitelisted"
		},

		["sias"] = {
		"sias.whitelisted"
		},
		["accestinta"] = {
		"permisie.tinta"
		},

		["pachetarme"] = {
		},

		["nitrobooster"] = {	
		"nitro.salariu"
		},

		["vipmenutest"] = {
		"vipmenu.test"
		},
		
		--

		["pepsy"] = {
			"admin.revivec",
			"admin.tptom"
		},

		["youtuber"] = {
			"youtuber.chat"			
		},

		["sponsor"] = {
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu"
		},
		["mafiapepsy"] = {
			"mafiepepsy.masini",
			"mafiepepsy.arme",
			"police.putinveh",
			"police.getoutveh",
			"police.drag",
			"vanzator.droguri",
			"police.menu",
			"mafia.arme"
		},
		--
		["mofo"] = {
		"mofo.vehicle"
		},
		["spike"] = {
		"spike.masina"
		},
		["slasher"] = {
			"slasher.masina",
			"traficant.acces"
		},
		["NorbSiMaruServer"] = {
			"NorbSiMaruServer.masina"
		},
		["fondator"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["dev"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["Community Manager"] = {
			_config = {onspawn = function(player) end},
			"player.giveMoney",
			"player.group.add",
			"eup.menu",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveitem",
			"admin.tickets",
			"admin.ajail",
			"admin.announce",
			"admin.menu",
			"admin.revivec",
			"admin.tptom",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"admin.easy_unjail",
			"ban.comanda",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"revive.player",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.spectate",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["supportdev"] = {
			_config = {onspawn = function(player) end},
			"admin.tickets",
			"admin.announce",
			"ban.comanda",
			"admin.revivec",
			"admin.tptom",
			"admin.menu",
			"admin.ajail",
			"admin.easy_unjail",
			"admin.godmode",
			"player.spectate",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"revive.player",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["Head Of Staff"] = {
			_config = {onspawn = function(player) end},
			"admin.ajail",
			"player.spectate",
			--"player.giveitem",
			"admin.tickets",
			"admin.announce",
			"admin.menu",
			--"cufar.event",
			--"cufar.boost",
			"admin.revivec",
			"admin.tptom",
			"ban.comanda",
			--"cufar.gur",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			--"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"revive.player",
			--"emergency.shop",
			"player.tpto"
		},
		["admin"] = {
			"admin.tickets",
			"admin.announce",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.ajail",
			"ban.comanda",
			"player.spectate",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"admin.revivec",
			"admin.tptom",
			"player.tptowaypoint",
			"player.kick",
			"player.ban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"revive.player",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["moderator"] = {
			"admin.tickets",
			"admin.announce",
			"revive.player",
			"player.list",
			"admin.ajail",
			"player.kick",
			"admin.deleteveh",
			"player.spectate",
			"admin.revivec",
			"admin.tptom",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto",
			"player.tpwaypoint"
		},
		["helper"] = {
			"admin.tickets",
			"admin.announce",
			"admin.ajail",
			"player.list",
			"player.kick",
			"revive.player",
			"player.coords",
			"player.tptome",
			"admin.revivec",
			"admin.deleteveh",
			"admin.tptom",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["trialhelper"] = {
			"admin.tickets",
			"player.coords",
			"admin.ajail",
			"admin.revivec",
			"admin.tptom",
			"respawn.acces",
			"admin.deleteveh",
			"player.tptome",
			"revive.player",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},	
		["skema"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.spectate",
			"player.group.remove",
			"admin.ajail",
			"eup.menu",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.tptowaypoint",
			"player.kick",
			"player.ban",
			"player.noclip",
			"player.spectate",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		-- GRUPA PE CARE O PRIMESTI LA INCEPUT
			["user"] = {
			_config = {
			onspawn = function(player) 	vRPclient.notify(player,{"Salut! Bine ai venit pe Liquid|Romania ~b~ ROMANIA~w~ ! Apasa [~o~F1~w~] sau [~o~K~w~] Pentru meniuri!"}) end
			},
			"player.phone",
			"player.calladmin",
			"player.fix_haircut",
			"player.check",
			--"mugger.mug",
			"police.askid",
			"player.check",
			"player.player_menu",
			"player.userlist",
			"user.arme",
			"police.seizable",	-- can be seized
			"user.salariu"
		},	
			["Somer"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"citizen.salariu"
		},
		["vip1"] = {
			"vip1.salariu",
			"vip1.masini"

		},
		["vip2"] = {
			"vip2.salariu",
			"vip1.masini",
			"packetvip2.acces",
			"vip2.masini"

		},
		["vip3"] = {
			"vip3.salariu",
			"vip1.masini",
			"vip2.masini",
			"vip3.masini"

		},
		["vip4"] = {
			"vip4.salariu",
			"sponsor.menu",
			"vip1.masini",
			"vip2.masini",
			"vip3.masini",
			"vip4.masini"

		},
		["premiumgur"] = {
			"premium.salariu",
			"premium.vehicle"
		},
			["Lawyer"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"Lawyer.vehicle",
				"Lawyer.whitelisted",
				"Lawyer.cloakroom",
				"Lawyer.salariu"
		},
			["Judge"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"judge.salariu",
			"Judge.whitelisted"
		},

			["Taxi Pelican"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"taxi.vehicle",
				"soferp.salariu",
				"taxi.service"
			},
				["Director SMURD"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"dspital.salariu",
					"eup.menu",
					"ems.mission"
				},
				["Sef Spital"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"emergency.service",
					"emscheck.revive",
					"emergency.cloakroom",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"eup.menu",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"dmedical.salariu",
					"ems.mission"
				},
				["Sef de Tura SMURD"] = {
					_config = { gtype = "job",
					onspawn = function(player) end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"emergency.service",
					"emergency.cloakroom",
					"emergency.vehicle",
					"emergency.market",
					"emscheck.revive",
					"eup.menu",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"chirurg.salariu",
					"ems.mission"
				},
				["Chirurg"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"police.pc",
					--"police.wanted",
					"medic.chat",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"stagiar.salariu",
					"ems.mission"
				},
				["Paramedic Smurd"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Asistent-Sef"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Asistent"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					"police.pc",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Mechanic"] = {
					_config = { gtype = "job",
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"repair.salariu"
				},
				["Dealer de Iarba"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"mission.drugseller.weed",
					"drugseller.market",
					"harvest.weed"
			},
			["Dealer de Cocaina"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"mission.drugseller.weed",
				"drugseller.market",
				"harvest.coca"
		},
		["Dealer de LSD"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"mission.drugseller.weed",
			"drugseller.market",
			"harvest.lsd"
		},
		["Fan Courier"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
	       "fan.vehicle"
		},
			["Hot de masini"] = {
				_config = { gtype = "job",
				onspawn = function(player) end
				},
				"lockpick.masini"
			},

		["Tirist"] = {
			_config = { gtype = "job",
			onspawn = function(player) end
			},
			"tirist.vehicle",
			"tirist.salariu"
		},		
		["Agent"] = {
			_config = { 
			gtype = "job",
			onjoin = function(player) vRPclient.setCop(player,{true}) end,
			onspawn = function(player) vRPclient.setCop(player,{true}) end,
			onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"agent.arme",
			"eup.menu",
			"radio.police",
			"police.pc",
			"agent.salariu",
			"officer.chat",
			"police.putinveh",
			"police.getoutveh",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.permis",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"police.carnet",
				"police.asigurare",
				"police.certificat",
				"confisca.permis",
				"verifica.permis",
				"verifica.buletin",
			"toggle.service",
			"police.freeze",
			"police.service",
			"police.wanted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"officer.vehicle",
			"police.announce",
		"-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"agent.arme",
			"cop.whitelisted",
			"emergency.market",
			"emergency.revive",
			"emergency.shop",
			--"player.list",
			"cadet.masini",
			"agp.masini",
			"officer.salariu",
			"police.mission",
			"police.menu_interaction"
		},
		
		["Agent S.I.A.S"] = {
			_config = { 
			gtype = "job",
			onjoin = function(player) vRPclient.setCop(player,{true}) end,
			onspawn = function(player) vRPclient.setCop(player,{true}) end,
			onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"agent.arme",
			"police.pc",
			"radio.police",
			"officer.chat",
			"police.putinveh",
			"agentp.salariu",
			"police.getoutveh",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"verifica.buletin",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.permis",
			"police.service",
			"police.wanted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"officer.vehicle",
			"police.announce",
	    	"-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"agent.arme",
			"sias.whitelisted",
			"emergency.market",
			"emergency.revive",
			"emergency.shop",
			--"player.list",
			"agp.masini",
			"police.mission",
			"police.menu_interaction"
		},	
		["Agent Sef"] = {  
			_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			"detective.chat",
			"agent.arme", 
			"police.putinveh",
			"radio.police",
			"police.getoutveh",
			"agents.salariu",
			"police.service",
			"police.wanted",
			"police.permis",
			"police.seize.weapons",
			"police.seize.items",
			"agp.masini",
			--"police.jail",
			"police.carnet",
				"police.asigurare",
				"police.certificat",
				"confisca.permis",
				"verifica.permis",
				"verifica.buletin",
			"cadet.masini",
			"detective.vehicle",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			-- "-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"detective.arme",
			"cop.whitelisted",
			"emergency.market",
			"emergency.revive",
			"emergency.shop",
			--"player.list",
			"detective.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Agent Sef S.I.A.S"] = {  
				_config = { 
					gtype = "job",
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"agentsp.salariu",
				"police.pc",
				"agent.arme", 
				"police.putinveh",
				"radio.police",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.permis",
				"police.seize.weapons",
				"police.seize.items",
				"verifica.buletin",
				"detective.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"detective.arme",
				"sias.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				--"player.list",
				"police.menu_interaction",
				"police.mission"
				},
			["Sub-Inspector"] = {  
				_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"subinspector.salariu",
				"radio.police",
                "ins.arme",
				"police.pc",
				"detective.chat",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.permis",
				"police.seize.weapons",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"detective.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"detective.arme",
				"sias.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				"subin.masini",
				--"player.list",
				"cadet.masini",
				"agp.masini",
				"detective.salariu",
				"police.menu_interaction",
				"police.mission"
			},
			["Inspector S.I.A.S"] = {  
			_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			--"police.handcuff",
			"agent.arme", 
			"inspector.salariu",
			"police.permis",
			"police.putinveh",
			"police.getoutveh",
			"radio.police",
			"police.service",
			"police.wanted",
			"verifica.buletin",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"cadet.masini",
			"agp.masini",
			--"police.fine",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			"sgt.vehicle",
			"-police.seizable",	
			"police.vehicle",
			"sergent.arme",
			"sias.whitelisted",
			"subin.masini",
			"emergency.market",
			"emergency.revive",
			"emergency.shop",
			--"player.list",
			"sergent.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Inspector-Sef"] = {  
				_config = { 
					gtype = "job",
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"police.pc",
				--"police.handcuff",
				"agent.arme", 
				"police.permis",
				"police.putinveh",
				"police.getoutveh",
				"radio.police",
				"inspectorp.salariu",
				"police.service",
				"police.wanted",
				"police.carnet",
				"verifica.buletin",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				"cadet.masini",
				"agp.masini",
				--"police.fine",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				"sgt.vehicle",
				"-police.seizable",	
				"police.vehicle",
				"sergent.arme",
				"cop.whitelisted",
				"subin.masini",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				--"player.list",
				"sergent.salariu",
				"police.menu_interaction",
				"police.mission"
				},
			["Comisar S.I.A.S"] = {  
			_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			--"police.handcuff",
			"police.permis",
			"subin.masini",
			"ins.arme",
			"police.carnet",
			"verifica.buletin",
			"cadet.masini",
			"agp.masini",
			"radio.police",
			"police.putinveh",
			"police.getoutveh",
			"police.service",
			"police.wanted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			--"police.fine",
			"subcomisar.salariu",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			"commander.vehicle",
			"bcco.masini",
			"police.seizable",	
			"police.vehicle",
			"comandant.arme",
			"sias.whitelisted",
			"emergency.market",
			"emergency.revive",
			"emergency.shop",
			--"player.list",
			"commander.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Comisar"] = {  
				_config = { 
					gtype = "job",
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"police.pc",
				--"police.handcuff",
				"police.permis",
				"subin.masini",
				"ins.arme",
				"police.carnet",
					"police.asigurare",
					"police.certificat",
					"confisca.permis",
					"verifica.permis",
					"verifica.buletin",
				"cadet.masini",
				"agp.masini",
				"comisar.salariu",
				"radio.police",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				--"police.fine",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				"commander.vehicle",
				"bcco.masini",
				"police.seizable",	
				"police.vehicle",
				"comandant.arme",
				"cop.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				--"player.list",
				"commander.salariu",
				"police.menu_interaction",
				"police.mission"
				},
			["Comisar Sef S.I.A.S"] = {  
				_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"radio.police",
				"police.pc",
				"ins.arme",
				"bcco.arme",
				"police.putinveh",
				"police.getoutveh",
				"police.permis",
				"comisars.salariu",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				"chief.vehicle",
				"verifica.buletin",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"sias.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				--"player.list",
				"bcco.masini",
				"cadet.masini",
				"agp.masini",
				"dchief.salariu",
				"police.menu_interaction",
				"police.mission"
			},
			["Chestor"] = {  
				_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"ins.arme",
				"bcco.arme",
				"police.pc",
				"agent.arme",
				"police.permis",
				--"police.handcuff",
				"radio.police",
				"chestor.salariu",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"police.carnet",
				"police.asigurare",
				"police.certificat",
				"confisca.permis",
				"verifica.permis",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"chief.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"chief.salariu",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
			    "cadet.masini",
		    	"agp.masini",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"cop.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				"bcco.masini",
				"subin.masini",
				"police.menu_interaction",
				"police.mission"
	},
			["Chestor Secundar S.I.A.S"] = {  
				_config = { 
				gtype = "job",
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"ins.arme",
				"bcco.arme",
				"police.pc",
				"agent.arme",
				"police.permis",
				--"police.handcuff",
				"radio.police",
				"police.putinveh",
				"police.getoutveh",
				"chestorp.salariu",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"chief.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"chief.salariu",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
			    "cadet.masini",
		    	"agp.masini",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"cop.whitelisted",
				"emergency.market",
				"emergency.revive",
				"emergency.shop",
				"bcco.masini",
				"subin.masini",
				"police.menu_interaction",
				"police.mission"
	},
	["Chestor General S.I.A.S"] = {  
		_config = { 
		gtype = "job",
		onjoin = function(player) vRPclient.setCop(player,{true}) end,
		onspawn = function(player) vRPclient.setCop(player,{true}) end,
		onleave = function(player) vRPclient.setCop(player,{true}) end
		},
		"police.radio",
		"eup.menu",
		"ins.arme",
		"bcco.arme",
		"police.pc",
		"agent.arme",
		"police.permis",
		--"police.handcuff",
		"chestors.salariu",
		"radio.police",
		"police.putinveh",
		"police.getoutveh",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"verifica.buletin",
		"police.seize.items",
		"police.jail",
		"chief.vehicle",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"chief.salariu",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.announce",
	-- "-police.store_weapons",
		"cadet.masini",
		"agp.masini",
		"-police.seizable",	
		"police.vehicle",
		"ins.arme",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		"bcco.masini",
		"subin.masini",
		"police.menu_interaction",
		"police.mission"
},
	["Chestor General"] = {  
		_config = { 
		gtype = "job",
		onjoin = function(player) vRPclient.setCop(player,{true}) end,
		onspawn = function(player) vRPclient.setCop(player,{true}) end,
		onleave = function(player) vRPclient.setCop(player,{true}) end
		},
		"police.radio",
		"eup.menu",
		"ins.arme",
		"bcco.arme",
		"police.pc",
		"agent.arme",
		"police.permis",
		--"police.handcuff",
		"radio.police",
		"police.putinveh",
		"police.getoutveh",
		"police.service",
		"police.wanted",
		"chestorg.salariu",
		"police.seize.weapons",
		"police.carnet",
		"police.asigurare",
		"police.certificat",
		"confisca.permis",
		"verifica.permis",
		"verifica.buletin",
		"police.seize.items",
		"police.jail",
		"chief.vehicle",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"chief.salariu",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.announce",
	-- "-police.store_weapons",
		"cadet.masini",
		"agp.masini",
		"-police.seizable",	
		"police.vehicle",
		"ins.arme",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		"bcco.masini",
		"subin.masini",
		"police.menu_interaction",
		"police.mission"
},
	               ------------------- JOB-URI
	["Vacar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Vacar"}) end
	  },
	  "job.salariu",
	  },
	  ["Traficant de Arme"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti traficant de arme"}) end
	  },
	  "traficant.arme"
	  },
	  ["Hitman"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti traficant de arme"}) end
	  },
	  "cautaprostu.hitman",
	  "armamenthitman.acces",
	  "jobhitman.acces",
	  "hitman.service",
	  "garajhitman.acces"
	  },
	  ["Lider Hitman"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti traficant de arme"}) end
	  },
	  "cautaprostu.hitman",
	  "armamenthitman.acces",
	  "jobhitman.acces",
	  "hitman.service",
	  "garajhitman.acces"
	  },

--===============[ JOBURI NOI ~ START]===============--

	  --[[["Postas"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti postas"}) end
  	  },
  		"job.salariu",
  		"suntpostas.plm"
 	  },]]
  	  ["Hacker"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti Hacker"}) end
  	  },
  		"sunthacker.plm",
  		"job.salariu",
  		"hacker.job"
  	  },
  	  --[[["Livrator Bancar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Faci parte din Banca. Livreaza bani!"}) end
  	  },
  		"job.salariu",
  		"suntlivratorbancar.plm"
  	  },]]
  	  ["Sofer Stivuitor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Sofer de Motostivuitor"}) end
  	  },
  		"moto.job",
  		"job.salariu"
	  },
	  ["Gunoier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la salubritate"}) end
  	  },
  		"job.salariu"
	  },
	  ["Sofer Autobuz"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Sofer de Autobuz"}) end
  	  },
  		"job.salariu"
	  },
	  ["Uber Eatz"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Uber Eatz"}) end
  	  },
  		"job.salariu"
	  },
	  ["Croitor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Croitorie"}) end
  	  },
  		"job.salariu"
	  },
	  ["Fan Courier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Fan Courier"}) end
  	  },
		  "job.salariu",
		  "fancurier.garaj"
	  },
	  ["Santierist"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi pe Santier"}) end
  	  },
		  "job.salariu"
	  },
	  ["Ciresar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi in livada de cirese"}) end
  	  },
		  "job.salariu"
	  },
	  ["Fermier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Ferma"}) end
  	  },
		  "job.salariu"
	  },

	  
--===============[ JOBURI NOI ~ FINISH]===============--
	  ["Lider La Famiglia"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"familia.masini",
		"familial.masini",
        "mafia.arme",
	},	
	["Co-Lider La Famiglia"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"familia.masini",
		"familial.masini",
        "mafia.arme",
	},	
	["La Famiglia"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "familia.masini",
        "mafia.arme",
	},
	["Lider Cosa Nostra"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"cosa.masini",
		"cosal.masini",
        "mafia.arme",
	},	
	["Co-Lider Cosa Nostra"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"cosa.masini",
		"cosal.masini",
        "mafia.arme",
	},	
	["Cosa Nostra"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "cosa.masini",
        "mafia.arme",
	},
	["Lider Maniacs"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"maniacs.masini",
		"maniacsl.masini",
        "mafia.arme",
	},	
	["Co-Lider Maniacs"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"maniacs.masini",
		"maniacsl.masini",
        "mafia.arme",
	},	
	["Maniacs"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "maniacs.masini",
        "mafia.arme",
	},		
	["Lider Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "curcubeu.masini",
        "mafia.arme",
	},		
	["Co-Lider Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "curcubeu.masini",
        "mafia.arme",
	},
	["Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "curcubeu.masini",
        "mafia.arme",
	},	
	["Lider LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "vagos.masini",
        "mafia.arme",
	},		
	["Co-Lider LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "vagos.masini",
        "mafia.arme",
	},
	["LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "vagos.masini",
		"mafia.arme",
	},
	  ["SONS OF ANARCHY"] = {
		"scu.cloakroom",
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "scu.masini",
        "mafia.arme",
        "scu.skin"		
	},	
	["Co-Lider SONS OF ANARCHY"] = {
		"scu.cloakroom",
        "police.putinveh",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
		"police.menu",
		"police.easy_cuff",
        "scu.masini",
        "mafia.arme",
        "scu.skin"		
	},	
	["Lider SONS OF ANARCHY"] = {
		"scu.cloakroom",
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
        "scu.masini",
        "mafia.arme",
        "scu.skin"		
	},
	  ["Constructor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca si Constructor"}) end
	  }

	}
}
-- GRUPE ID 1
cfg.users = {
  [1] = { -- II DA OWNER-ULUI URMATOARELE GRADE:
		"superadmin",
		"dev",
		"Community Manager",
		"recruiter",
  }
}

-- GRUPE DE LUAT
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["Agentia Fortelor de Munca"] = {
    _config = {x = -1083.0966796875, y = -248.15505981445, z = 37.763290405273},
	"Mechanic",
	"Tirist",
	"Vacar",
	"Taxi Pelican",
	--"Postas",
	--"Livrator Banca",
	"Sofer Stivuitor",
	--"Fan Courier",
	"Santierist",
	"Ciresar",
	"Fermier",	
    "Somer"
  },
  ["Agentia Fortelor de Munca #2"] = { 
    _config = {x = -1081.3146972656, y = -247.17333984375, z = 37.763278961182, permissions = {"amjoburipeserver.inpulamea"} },
    "Somer"
  },
  ["Job Stivuitor"] = {
    _config = {x = 152.45585632324, y = -3105.0861816406, z = 5.8963098526001},
	"Sofer Stivuitor",
    "Somer"
  },
  --[[["Hitman"] = {
    _config = {x = -1911.9273681641, y = -569.71649169922, z = 19.097215652466, blipid = 351, blipcolor = 7, permissions = {"jobhitman.acces"} },
    "Hitman",
	"Somer"
  },
  ["Judge"] = {
    _config = {x = -59.127178192139, y = 359.25082397461, z = 113.05643463135, blipid = 351, blipcolor = 7, permissions = {"Judge.whitelisted"} },
    "Judge",
	"Somer"
  },]]
  ["Tirist job"] = {
    _config = {x = -57.001544952392, y = -2448.6643066406, z = 7.2357635498046, blipid = 477, blipcolor = 3},
    "Tirist",
    "Somer"
  }  

}

return cfg
