
	local cfg = {}


	cfg.groups = {
-- SISTEME
		["wanted"] = {

		},
				
		["afacerist"] = {
		
		},	
		["jailer"] = {
		
		},
		["jaile2"] = {
		
		},
		["spargator"] = {		
		},

		["esk"] = {
		},
		["ems"] = {
		"ems.whitelisted"
		},

		["cop"] = {
		"cop.whitelisted"
		},
		["bypassbanca"] = {
		},

		["sias"] = {
		"sias.whitelisted"
		},
		["accestinta"] = {
		"permisie.tinta"
		},
		["accessleep"] = {
			"acces.sleep"
		},

		["pachetarme"] = {
		},

		["nitrobooster"] = {	
		"nitro.salariu"
		},

		["vipmenutest"] = {
		"vipmenu.test"
		},
		["test"] = {
			"test.masina"
		},
		
		
		["Traficant"] = {
		"traficant.acces",
		"traficant.service"
		},

		["pepsy"] = {
			"admin.revivec",
			"admin.tptom"
		},

		["youtuber"] = {
			"youtuber.chat"			
		},

		["sponsor"] = {
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu"
		},
		["mafiapepsy"] = {
			"mafiepepsy.masini",
			"mafiepepsy.arme",
			"police.putinveh",
			"police.getoutveh",
			"police.drag",
			"vanzator.droguri",
			"police.menu",
			"mafia.arme"
		},
		
		["mofo"] = {
		"mofo.vehicle"
		},
		["flg"] = {
			"flg.vehicle"
		},
		["hades"] = {
		"hades.masina"
		},
		["spike"] = {
		"spike.masina"
		},
		["slasher"] = {
			"slasher.masina"
		},
		["seba"] = {
			"seba.masina"
		},
		["zavy"] = {
			"zavy.masina"
		},
		["soa"] = {
			"soa.masina"
		},
		["cris"] = {
			"cris.masina"
		},
		["alexene"] = {
			"alexene.masina"
		},
		["vito"] = {
			"vito.masina"
		},
		["orlando"] = {
			"orlando.masina"
		},
		["NorbSiMaruServer"] = {
			"NorbSiMaruServer.masina"
		},
		["flocea"] = {
			"flocea.masina"
		},
		["dorian"] = {
			"dorian.skin"
		},
		["marchi"] = {
			"marchi.masina"
		},
		["Titel"] = {
			"titel.masina"
		},
		["Remus"] = {
			"remus.masina"
		},
		["dallas"] = {
			"dallas.masina"
		},
		["alexander"] = {
			"alexander.masina"
		},
		["acces.duty"] = {
			"acces.duty"
		},
		["fondator"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"staff.duty",
			"acces.restart",
			"vip1.masini",
			"id.admin",
			"chocohax.adminmenu", 
			"chocohax.noclip", 
			"chocohax.esp",
			"chocohax.vehicles",
			"chocohax.weapons", 
			"chocohax.blips",
			"chocohax.debugMenu",
			"chocohax.teleports",
			"chocohax.showcoords",
			"chocohax.reloadbans",
			"chocohax.cleararea", 
			"chocohax.kick",
			"chocohax.mute",
			"chocohax.ban",
			"chocohax.unban",
			"chocohax.admincmds",
			"chocohax.requestidentifiers", 
			"chocohax.spectate", 
			"chocohax.screenshot", 
			"chocohax.resourcechecker",
			"vip2.masini",
			"vip3.masini",
			"stop.chat",
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu",
			"tickete.check",
			"tickete.clear",
			"say.chat",
			"player.VanishBan",
			"vMenu.Staff",
			"permisie.tinta",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"add.faction",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},

		["Co-Fondator"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"staff.duty",
			"acces.restart",
			"vip1.masini",
			"chocohax.adminmenu", 
			"chocohax.noclip", 
			"chocohax.esp",
			"chocohax.vehicles",
			"chocohax.weapons", 
			"chocohax.blips",
			"chocohax.debugMenu",
			"chocohax.teleports",
			"chocohax.showcoords",
			"chocohax.reloadbans",
			"chocohax.cleararea", 
			"chocohax.kick",
			"chocohax.mute",
			"chocohax.ban",
			"chocohax.unban",
			"chocohax.admincmds",
			"chocohax.requestidentifiers", 
			"chocohax.spectate", 
			"chocohax.screenshot", 
			"chocohax.resourcechecker",
			"vip2.masini",
			"vip3.masini",
			"stop.chat",
			"sponsor.chat",
			"id.admin",
			"sponsor.salariu",
			"sponsor.menu",
			"tickete.check",
			"tickete.clear",
			"say.chat",
			"player.VanishBan",
			"vMenu.Staff",
			"permisie.tinta",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"add.faction",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},

		["ary"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"staff.duty",
			"vip1.masini",
			"vip2.masini",
			"vip3.masini",
			"chocohax.adminmenu", 
			"chocohax.noclip", 
			"chocohax.esp",
			"chocohax.vehicles",
			"chocohax.weapons", 
			"chocohax.blips",
			"chocohax.debugMenu",
			"chocohax.teleports",
			"chocohax.showcoords",
			"chocohax.reloadbans",
			"chocohax.cleararea", 
			"chocohax.kick",
			"chocohax.mute",
			"chocohax.ban",
			"chocohax.unban",
			"chocohax.admincmds",
			"chocohax.requestidentifiers", 
			"chocohax.spectate", 
			"chocohax.screenshot", 
			"chocohax.resourcechecker",
			"id.admin",
			"stop.chat",
			"acces.restart",
			"tickete.clear",
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu",
			"say.chat",
			"player.VanishBan",
			"vMenu.Staff",
			"permisie.tinta",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"add.faction",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"tickete.check",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["dev"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"staff.duty",
	 "chocohax.adminmenu", 
	"chocohax.noclip", 
	"chocohax.esp",
	"chocohax.vehicles",
	"chocohax.weapons", 
	"chocohax.blips",
	"chocohax.debugMenu",
	"chocohax.teleports",
	"chocohax.showcoords",
	"chocohax.reloadbans",
	"chocohax.cleararea", 
	"chocohax.kick",
	"chocohax.mute",
	"chocohax.ban",
	"chocohax.unban",
	"chocohax.admincmds",
	"chocohax.requestidentifiers", 
	"chocohax.spectate", 
	"chocohax.screenshot", 
	"chocohax.resourcechecker",
			"vip1.masini",
			"id.admin",
			"vip2.masini",
			"vip3.masini",
			"stop.chat",
			"acces.restart",
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu",
			"say.chat",
			"tickete.check",
			"tickete.clear",
			"say.smeker",
			"player.VanishBan",
			"vMenu.Staff",
			"permisie.tinta",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"add.faction",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["Community Manager"] = {
			_config = {onspawn = function(player) end},
			"player.group.add",
			"staff.duty",
			"vip1.masini",
			"vip2.masini",
			"vip3.masini",
			"chocohax.adminmenu", 
			"chocohax.noclip", 
			"chocohax.esp",
			"chocohax.vehicles",
			"chocohax.weapons", 
			"chocohax.blips",
			"chocohax.debugMenu",
			"chocohax.teleports",
			"chocohax.showcoords",
			"chocohax.reloadbans",
			"chocohax.cleararea", 
			"chocohax.kick",
			"chocohax.mute",
			"chocohax.ban",
			"chocohax.unban",
			"chocohax.admincmds",
			"chocohax.requestidentifiers", 
			"chocohax.spectate", 
			"chocohax.screenshot", 
			"chocohax.resourcechecker",
			"stop.chat",
			"acces.restart",
			"say.chat",
			"player.VanishBan",
			"id.admin",
			"sponsor.chat",
			"sponsor.salariu",
			"sponsor.menu",
			"tickete.check",
			"tickete.clear",
			"vMenu.Staff",
			"permisie.tinta",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"add.faction",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["supportdev"] = {
			_config = {onspawn = function(player) end},
			"admin.tickets",
			"staff.duty",
			"id.admin",
			"acces.restart",
			"chocohax.adminmenu", 
			"chocohax.noclip", 
			"chocohax.esp",
			"chocohax.vehicles",
			"chocohax.weapons", 
			"chocohax.blips",
			"chocohax.debugMenu",
			"chocohax.teleports",
			"chocohax.showcoords",
			"chocohax.reloadbans",
			"chocohax.cleararea", 
			"chocohax.kick",
			"chocohax.mute",
			"chocohax.ban",
			"chocohax.unban",
			"chocohax.admincmds",
			"chocohax.requestidentifiers", 
			"chocohax.spectate", 
			"chocohax.screenshot", 
			"chocohax.resourcechecker",
			"sponsor.chat",
			"sponsor.salariu",
			"vip1.masini",
			"vip2.masini",
			"vip3.masini",
			"sponsor.menu",
			"player.VanishBan",
			"stop.chat",
			"admin.announce",
			"vMenu.Staff",
			"ban.comanda",
			"tickete.check",
			"tickete.clear",
			"say.chat",
			"admin.revivec",
			"admin.tptom",
			"admin.menu",
			"admin.ajail",
			"admin.easy_unjail",
			"admin.godmode",
			"player.spectate",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"revive.player",
			"player.ban",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["Head Of Staff"] = {
			_config = {onspawn = function(player) end},
			"admin.ajail",
			"staff.duty",
			"acces.restart",
			"player.VanishBan",
			"tickete.check",
			"tickete.clear",
			"say.chat",
			"player.spectate",
			"stop.chat",
			--"player.giveitem",
			"admin.tickets",
			"admin.announce",
			"admin.menu",
			--"cufar.event",
			--"cufar.boost",
			"admin.revivec",
			"admin.tptom",
			"ban.comanda",
			--"cufar.gur",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			--"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.ban",
			"player.unban",
			"player.noclip",
			"add.faction",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"revive.player",
			--"emergency.shop",
			"player.tpto"
		},
		["admin"] = {
			"admin.tickets",
			"staff.duty",
			"stop.chat",
			"admin.announce",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.ajail",
			"ban.comanda",
			"player.spectate",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"admin.revivec",
			"admin.tptom",
			"add.faction",
			"player.tptowaypoint",
			"player.kick",
			"player.ban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"revive.player",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["moderator"] = {
			"admin.tickets",
			"staff.duty",
			"stop.chat",
			"admin.announce",
			"revive.player",
			"player.list",
			"admin.ajail",
			"player.kick",
			"admin.deleteveh",
			"player.spectate",
			"admin.revivec",
			"admin.tptom",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto",
			"player.tpwaypoint"
		},
		["helper"] = {
			"admin.tickets",
			"staff.duty",
			"admin.announce",
			"admin.ajail",
			"player.list",
			"player.kick",
			"revive.player",
			"player.coords",
			"player.tptome",
			"admin.revivec",
			"admin.deleteveh",
			"admin.tptom",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["trialhelper"] = {
			"admin.tickets",
			"staff.duty",
			"player.coords",
			"admin.ajail",
			"admin.revivec",
			"admin.tptom",
			"respawn.acces",
			"admin.deleteveh",
			"player.tptome",
			"revive.player",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},	
		["skema"] = {
			_config = {onspawn = function(player) end},
			--"player.group.add",
			--"player.group.add.superadmin",
			--"player.group.add.admin", 
			"player.group.add",
			"staff.duty",
			"player.spectate",
			"player.group.add.superadmin",
			"player.group.add.admin", 
			"player.group.remove",
			"player.giveMoney",
			"daurestart.cassmecher",
			"ban.comanda",
			"cufar.event",
			"cufar.boost",
			"cufar.gur",
			"player.giveitem",
			"admin.ajail",
			"admin.tickets",
			"eup.menu",
			"admin.revivec",
			"admin.tptom",
			"admin.announce",
			"admin.menu",
			"admin.easy_unjail",
			"admin.spikes",
			"admin.godmode",
			"admin.spawnveh",
			"admin.deleteveh",
			"player.blips",
			"player.tptowaypoint",
			"player.list",
			"player.whitelist",
			"player.unwhitelist",
			"player.kick",
			"player.VanishBan",
			"player.unban",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		["vdn"] = {
			_config = {onspawn = function(player) end},
			"staff.duty",
			"admin.revivec",
			"admin.tptom",
			"admin.menu",
			"admin.godmode",
			"player.blips",
			"player.tptowaypoint",
			"player.noclip",
			"player.coords",
			"player.tptome",
			"emergency.revive",
			"emergency.shop",
			"player.tpto"
		},
		-- GRUPA PE CARE O PRIMESTI LA INCEPUT
			["user"] = {
			_config = {
			onspawn = function(player) 	vRPclient.notify(player,{"Salut! Bine ai venit pe Liquid|Romania ~b~ ROMANIA~w~ ! Apasa [~o~F1~w~] sau [~o~K~w~] Pentru meniuri!"}) end
			},
			"player.phone",
			"player.calladmin",
			"player.fix_haircut",
			"player.check",
			--"mugger.mug",
			"police.askid",
			"player.check",
			"player.player_menu",
			"player.userlist",
			"user.arme",
			"police.seizable",	-- can be seized
			"user.salariu"
		},	
			["Somer"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"citizen.salariu"
		},
		["vip1"] = {
			"vip1.salariu",
			"vip1.vehicle"

		},
		["vip2"] = {
			"vip2.salariu",
			"vip1.vehicle",
			"vip2.vehicle"

		},
		["vip3"] = {
			"vip3.salariu",
			"vip1.vehicle",
			"vip2.vehicle",
			"vip3.vehicle"

		},
		["vip4"] = {
			"vip4.salariu",
		--	"sponsor.menu",
			"vip1.vehicle",
			"vip2.vehicle",
			"vip3.vehicle",
			"vip4.vehicle"

		},
		["premiumgur"] = {
			"premium.salariu",
			"premium.vehicle"
		},
			["Lawyer"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"Lawyer.vehicle",
				"Lawyer.whitelisted",
				"Lawyer.cloakroom",
				"Lawyer.salariu"
		},
			["Judge"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"judge.salariu",
			"Judge.whitelisted"
		},

			["Taxi Pelican"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"taxi.vehicle",
				"soferp.salariu",
				"taxi.service"
			},
				["Director SMURD"] = {
					_config = {
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"verifica.buletin",
					"bypass.radar",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					"police.askid",
					--"player.list",
					"police.menu_interaction",
					"dspital.salariu",
					"eup.menu",
					"ems.mission"
				},
				["Sef Spital"] = {
					_config = { 
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"police.askid",
					"emergency.service",
					"verifica.buletin",
					"emscheck.revive",
					"emergency.cloakroom",
					"emergency.vehicle",
					"bypass.radar",
					"emergency.market",
					"ems.whitelisted",
					"eup.menu",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"dmedical.salariu",
					"ems.mission"
				},
				["Sef de Tura SMURD"] = {
					_config = {
					onspawn = function(player) end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"emergency.service",
					"emergency.cloakroom",
					"verifica.buletin",
					"emergency.vehicle",
					"police.askid",
					"emergency.market",
					"bypass.radar",
					"emscheck.revive",
					"eup.menu",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"chirurg.salariu",
					"ems.mission"
				},
				["Chirurg"] = {
					_config = {
					onspawn = function(player)  end
					},
					"emergency.revive",
					--"police.wanted",
					"medic.chat",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"verifica.buletin",
					"police.askid",
					"bypass.radar",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"stagiar.salariu",
					"ems.mission"
				},
				["Paramedic Smurd"] = {
					_config = {
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"verifica.buletin",
					"police.askid",
					"emergency.vehicle",
					"emergency.market",
					"bypass.radar",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Asistent-Sef"] = {
					_config = { 
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"police.askid",
					"emscheck.revive",
					"bypass.radar",
					"emergency.vehicle",
					"verifica.buletin",
					"police.askid",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Asistent"] = {
					_config = { 
					onspawn = function(player)  end
					},
					"emergency.revive",
					"medic.chat",
					--"police.wanted",
					"emergency.shop",
					"eup.menu",
					"emergency.service",
					"emergency.cloakroom",
					"emscheck.revive",
					"emergency.vehicle",
					"verifica.buletin",
					"bypass.radar",
					"police.askid",
					"emergency.market",
					"ems.whitelisted",
					"ems.loadshop",
					--"player.list",
					"police.menu_interaction",
					"ems.salariu",
					"ems.mission"
				},
				["Mecanic"] = {
					_config = { gtype = "job",
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"mecanic.acces",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"repair.salariu"
				},

				["Ucenic Mecanic"] = {
					_config = { 
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"mecanic.acces",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"police.putinveh",
					"police.easy_cuff",
					"police.getoutveh",
					"police.drag",
					"police.menu",
					"sniper.acces",
					"mafiot.chat",
					"repair.salariu"
				},
				["Mecanic Sef"] = {
					_config = { 
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"mecanic.acces",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"police.putinveh",
					"police.easy_cuff",
					"police.getoutveh",
					"police.drag",
					"police.menu",
					"sniper.acces",
					"mafiot.chat",
					"repair.salariu"
				},
				["Responsabil Mecanic"] = {
					_config = { 
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"mecanic.acces",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"police.putinveh",
					"police.easy_cuff",
					"police.getoutveh",
					"police.drag",
					"police.menu",
					"sniper.acces",
					"mafiot.chat",
					"repair.salariu"
				},
				["Proprietar Service"] = {
					_config = {
					onspawn = function(player) end
					},
					"vehicle.repair",
					"vehicle.replace",
					"mecanic.acces",
					"repair.service",
					"mission.repair.satellite_dishes",
					"mission.repair.wind_turbines",
					"repair.vehicle",
					"repair.market",
					"police.putinveh",
					"police.easy_cuff",
					"police.getoutveh",
					"police.drag",
					"police.menu",
					"sniper.acces",
					"mafiot.chat",
					"repair.salariu"
				},
				["Dealer de Iarba"] = {
					_config = { gtype = "job",
					onspawn = function(player)  end
					},
					"mission.drugseller.weed",
					"drugseller.market",
					"harvest.weed"
			},
			["Dealer de Cocaina"] = {
				_config = { gtype = "job",
				onspawn = function(player)  end
				},
				"mission.drugseller.weed",
				"drugseller.market",
				"harvest.coca"
		},
		["Dealer de LSD"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
			"mission.drugseller.weed",
			"drugseller.market",
			"harvest.lsd"
		},
		["Fan Courier"] = {
			_config = { gtype = "job",
			onspawn = function(player)  end
			},
	       "fan.vehicle"
		},
			["Hot de masini"] = {
				_config = { gtype = "job",
				onspawn = function(player) end
				},
				"lockpick.masini"
			},
			["Hot de case"] = {
				_config = { gtype = "job",
				onspawn = function(player) end
				},
				"hotdecase.acces"
			},

		["Tirist"] = {
			_config = { gtype = "job",
			onspawn = function(player) end
			},
			"tirist.vehicle",
			"tirist.salariu"
		},		
		["Agent"] = {
			_config = { 
			onjoin = function(player) vRPclient.setCop(player,{true}) end,
			onspawn = function(player) vRPclient.setCop(player,{true}) end,
			onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"agent.arme",
			"eup.menu",
			"radio.police",
			"police.pc",
			"agent.salariu",
			"officer.chat",
			"police.putinveh",
			"police.getoutveh",
			"police.drag",
			"police.easy_cuff",
			"bypass.radar",
			"police.easy_fine",
			"police.easy_jail",
			"police.permis",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"politie.acces",
			"verifica.buletin",
			"toggle.service",
			"police.freeze",
			"police.service",
			"police.wanted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"officer.vehicle",
			"police.announce",
		"-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"agent.arme",
			"cop.whitelisted",
			--"player.list",
			"cadet.masini",
			"agp.masini",
			"officer.salariu",
			"police.mission",
			"police.menu_interaction"
		},
		
		["Agent S.I.A.S"] = {
			_config = { 
			onjoin = function(player) vRPclient.setCop(player,{true}) end,
			onspawn = function(player) vRPclient.setCop(player,{true}) end,
			onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"agent.arme",
			"police.pc",
			"radio.police",
			"officer.chat",
			"police.putinveh",
			"agentp.salariu",
			"police.getoutveh",
			"police.drag",
			"bypass.radar",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"sias.acces",
			"verifica.buletin",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.permis",
			"police.service",
			"police.wanted",
			"cop.whitelisted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"officer.vehicle",
			"police.announce",
	    	"-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"agent.arme",
			"sias.whitelisted",
			--"player.list",
			"agp.masini",
			"police.mission",
			"police.menu_interaction"
		},	
		["Agent Sef"] = {  
			_config = { 
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			"detective.chat",
			"agent.arme", 
			"police.putinveh",
			"radio.police",
			"police.getoutveh",
			"agents.salariu",
			"bypass.radar",
			"police.service",
			"police.wanted",
			"police.permis",
			"police.seize.weapons",
			"police.seize.items",
			"agp.masini",
			--"police.jail",
			"politie.acces",
			"verifica.buletin",
			"cadet.masini",
			"detective.vehicle",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			-- "-police.store_weapons",
			"-police.seizable",	
			"police.vehicle",
			"detective.arme",
			"cop.whitelisted",
			--"player.list",
			"detective.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Agent Sef S.I.A.S"] = {  
				_config = { 
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"agentsp.salariu",
				"police.pc",
				"agent.arme", 
				"police.putinveh",
				"radio.police",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.permis",
				"police.seize.weapons",
				"police.seize.items",
				"bypass.radar",
				"sias.acces",
				"verifica.buletin",
				"detective.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"cop.whitelisted",
				"detective.arme",
				"sias.whitelisted",

				--"player.list",
				"police.menu_interaction",
				"police.mission"
				},
			["Sub-Inspector"] = {  
				_config = {
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"subinspector.salariu",
				"radio.police",
				"ins.arme",
				"bypass.radar",
				"police.pc",
				"detective.chat",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"politie.acces",
				"cop.whitelisted",
				"verifica.buletin",
				"detective.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"detective.arme",
				"sias.whitelisted",

				"subin.masini",
				--"player.list",
				"cadet.masini",
				"agp.masini",
				"detective.salariu",
				"police.menu_interaction",
				"police.mission"
			},
			["Inspector S.I.A.S"] = {  
			_config = { 
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			--"police.handcuff",
			"agent.arme", 
			"inspector.salariu",
			"bypass.radar",
			"police.permis",
			"police.putinveh",
			"police.getoutveh",
			"radio.police",
			"police.service",
			"police.wanted",
			"sias.acces",
			"verifica.buletin",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			"cadet.masini",
			"agp.masini",
			--"police.fine",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"cop.whitelisted",
			"police.spikes",
			"police.menu",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			"sgt.vehicle",
			"-police.seizable",	
			"police.vehicle",
			"sergent.arme",
			"sias.whitelisted",
			"subin.masini",

			--"player.list",
			"sergent.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Inspector-Sef"] = {  
				_config = { 
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"police.pc",
				--"police.handcuff",
				"agent.arme", 
				"police.permis",
				"police.putinveh",
				"bypass.radar",
				"police.getoutveh",
				"radio.police",
				"inspectorp.salariu",
				"police.service",
				"police.wanted",
				"police.carnet",
				"verifica.buletin",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				"cadet.masini",
				"agp.masini",
				--"police.fine",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				"sgt.vehicle",
				"-police.seizable",	
				"police.vehicle",
				"sergent.arme",
				"cop.whitelisted",
				"subin.masini",

				--"player.list",
				"sergent.salariu",
				"police.menu_interaction",
				"police.mission"
				},
			["Comisar S.I.A.S"] = {  
			_config = {
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
			},
			"police.radio",
			"eup.menu",
			"police.pc",
			--"police.handcuff",
			"police.permis",
			"subin.masini",
			"ins.arme",
			"sias.acces",
			"verifica.buletin",
			"bypass.radar",
			"cadet.masini",
			"agp.masini",
			"radio.police",
			"police.putinveh",
			"police.getoutveh",
			"police.service",
			"police.wanted",
			"police.seize.weapons",
			"police.seize.items",
			"police.jail",
			--"police.fine",
			"subcomisar.salariu",
			"police.drag",
			"police.easy_cuff",
			"police.easy_fine",
			"police.easy_jail",
			"police.easy_unjail",
			"police.spikes",
			"police.menu",
			"cop.whitelisted",
			"police.check",
			"toggle.service",
			"police.freeze",
			"police.announce",
			"commander.vehicle",
			"bcco.masini",
			"police.seizable",	
			"police.vehicle",
			"comandant.arme",
			"sias.whitelisted",

			--"player.list",
			"commander.salariu",
			"police.menu_interaction",
			"police.mission"
			},
			["Comisar"] = {  
				_config = { 
					onjoin = function(player) vRPclient.setCop(player,{true}) end,
					onspawn = function(player) vRPclient.setCop(player,{true}) end,
					onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"police.pc",
				--"police.handcuff",
				"police.permis",
				"subin.masini",
				"bypass.radar",
				"ins.arme",
				"politie.acces",
				"verifica.buletin",
				"cadet.masini",
				"agp.masini",
				"comisar.salariu",
				"radio.police",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				--"police.fine",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				"commander.vehicle",
				"bcco.masini",
				"police.seizable",	
				"police.vehicle",
				"comandant.arme",
				"cop.whitelisted",

				--"player.list",
				"commander.salariu",
				"police.menu_interaction",
				"police.mission"
				},
			["Comisar Sef S.I.A.S"] = {  
				_config = { 
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"radio.police",
				"police.pc",
				"ins.arme",
				"bcco.arme",
				"police.putinveh",
				"police.getoutveh",
				"comisars.salariu",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"police.seize.items",
				"police.jail",
				"bypass.radar",
				"chief.vehicle",
				"sias.acces",
				"verifica.buletin",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
				"cop.whitelisted",
			-- "-police.store_weapons",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"sias.whitelisted",

				--"player.list",
				"bcco.masini",
				"cadet.masini",
				"agp.masini",
				"dchief.salariu",
				"police.menu_interaction",
				"police.mission"
			},
			["Chestor"] = {  
				_config = { 
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"ins.arme",
				"bcco.arme",
				"police.pc",
				"agent.arme",
				"police.permis",
				--"police.handcuff",
				"bypass.radar",
				"radio.police",
				"chestor.salariu",
				"police.putinveh",
				"police.getoutveh",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"politie.acces",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"chief.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"chief.salariu",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
			    "cadet.masini",
		    	"agp.masini",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"cop.whitelisted",

				"bcco.masini",
				"subin.masini",
				"police.menu_interaction",
				"police.mission"
	},
			["Chestor Secundar S.I.A.S"] = {  
				_config = { 
				onjoin = function(player) vRPclient.setCop(player,{true}) end,
				onspawn = function(player) vRPclient.setCop(player,{true}) end,
				onleave = function(player) vRPclient.setCop(player,{true}) end
				},
				"police.radio",
				"eup.menu",
				"ins.arme",
				"bcco.arme",
				"police.pc",
				"bypass.radar",
				"agent.arme",
				"police.permis",
				--"police.handcuff",
				"radio.police",
				"police.putinveh",
				"police.getoutveh",
				"chestorp.salariu",
				"police.service",
				"police.wanted",
				"police.seize.weapons",
				"sias.acces",
				"verifica.buletin",
				"police.seize.items",
				"police.jail",
				"chief.vehicle",
				"police.drag",
				"police.easy_cuff",
				"police.easy_fine",
				"police.easy_jail",
				"police.easy_unjail",
				"police.spikes",
				"chief.salariu",
				"police.menu",
				"police.check",
				"toggle.service",
				"police.freeze",
				"police.announce",
			-- "-police.store_weapons",
			    "cadet.masini",
		    	"agp.masini",
				"-police.seizable",	
				"police.vehicle",
				"ins.arme",
				"cop.whitelisted",

				"bcco.masini",
				"subin.masini",
				"police.menu_interaction",
				"police.mission"
	},
	["Chestor General S.I.A.S"] = {  
		_config = { 
		onjoin = function(player) vRPclient.setCop(player,{true}) end,
		onspawn = function(player) vRPclient.setCop(player,{true}) end,
		onleave = function(player) vRPclient.setCop(player,{true}) end
		},
		"police.radio",
		"eup.menu",
		"ins.arme",
		"bcco.arme",
		"bypass.radar",
		"police.pc",
		"agent.arme",
		"police.permis",
		--"police.handcuff",
		"chestors.salariu",
		"radio.police",
		"police.putinveh",
		"police.getoutveh",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"politie.acces",
		"sias.acces",
		"verifica.buletin",
		"police.seize.items",
		"police.jail",
		"chief.vehicle",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"chief.salariu",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.announce",
	-- "-police.store_weapons",
		"cadet.masini",
		"agp.masini",
		"-police.seizable",	
		"police.vehicle",
		"ins.arme",
		"cop.whitelisted",

		"bcco.masini",
		"subin.masini",
		"police.menu_interaction",
		"police.mission"
},
	["Chestor General"] = {  
		_config = { 
		onjoin = function(player) vRPclient.setCop(player,{true}) end,
		onspawn = function(player) vRPclient.setCop(player,{true}) end,
		onleave = function(player) vRPclient.setCop(player,{true}) end
		},
		"police.radio",
		"eup.menu",
		"ins.arme",
		"bcco.arme",
		"police.pc",
		"bypass.radar",
		"agent.arme",
		"police.permis",
		--"police.handcuff",
		"radio.police",
		"police.putinveh",
		"police.getoutveh",
		"police.service",
		"police.wanted",
		"chestorg.salariu",
		"police.seize.weapons",
		"politie.acces",
		"sias.acces",
		"verifica.buletin",
		"police.seize.items",
		"police.jail",
		"chief.vehicle",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"chief.salariu",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.announce",
	-- "-police.store_weapons",
		"cadet.masini",
		"agp.masini",
		"-police.seizable",	
		"police.vehicle",
		"ins.arme",
		"cop.whitelisted",

		"bcco.masini",
		"subin.masini",
		"police.menu_interaction",
		"police.mission"
},
	               ------------------- JOB-URI
	["Vacar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Vacar"}) end
	  },
	  "job.salariu",
	  },
	  ["Traficant de Arme"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti traficant de arme"}) end
	  },
	  "traficant.arme"
	  },
	  ["Hitman"] = {
		_config = {
		onspawn = function(player) vRPclient.notify(player,{"Esti Hitman"}) end
	  },
	  "cautaprostu.hitman",
	  "armamenthitman.acces",
	  "jobhitman.acces",
	  "hitman.service",
	  "police.menu",
	  "police.putinveh",
	  "police.getoutveh",
	  "police.drag",
	  "police.easy_cuff",
	  "garajhitman.acces"
	  },
	  ["Lider Hitman"] = {
		_config = {
		onspawn = function(player) vRPclient.notify(player,{"Esti Lider Hitman"}) end
	  },
	  "cautaprostu.hitman",
	  "armamenthitman.acces",
	  "jobhitman.acces",
	  "hitman.service",
	  "police.menu",
	  "police.putinveh",
	  "police.getoutveh",
	  "police.drag",
	  "police.easy_cuff",
	  "garajhitman.acces"
	  },

--===============[ JOBURI NOI ~ START]===============--

	  ["Postas"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti postas"}) end
  	  },
  		"job.salariu",
  		"suntpostas.plm"
 	  },
  	  ["Hacker"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti Hacker"}) end
  	  },
  		"sunthacker.plm",
		  "hacker.credit_cards",
		  "hacker.hack",
  		"job.salariu",
  		"hacker.job"
  	  },
  	  ["Sofer Bancar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Faci parte din Banca. Livreaza bani!"}) end
  	  },
  		"job.salariu"
  	  },
  	  ["Sofer Stivuitor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Sofer de Motostivuitor"}) end
  	  },
  		"moto.job",
  		"job.salariu"
	  },
	  ["Gunoier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la salubritate"}) end
  	  },
  		"job.salariu"
	  },
	  ["Pescar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Esti pescar."}) end
  	  },
		  "job.salariu",
		  "pescar.acces"
	  },
	  ["Sofer Autobuz"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Sofer de Autobuz"}) end
  	  },
  		"job.salariu"
	  },

	  ["Miner"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Miner"}) end
  	  },
  		"job.salariu"
	  },

	  ["Uber Eatz"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Uber Eatz"}) end
  	  },
  		"job.salariu"
	  },

	  ["Uber"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Uber "}) end
  	  },
  		"job.salariu",
		"uber.masina"
	  },

	  ["Croitor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Croitorie"}) end
  	  },
  		"job.salariu"
	  },
	  ["Fan Curier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Fan Courier"}) end
  	  },
		  "job.salariu",
		  "fancurier.garaj"
	  },
	  ["Padurar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca Padurar"}) end
  	  },
		  "job.salariu"
	  },
	  ["Ciresar"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi in livada de cirese"}) end
  	  },
		  "job.salariu"
	  },
	  ["Fermier"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi la Ferma"}) end
  	  },
		  "job.salariu"
	  },
	  ["Constructor"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient.notify(player,{"Lucrezi ca si Constructor"}) end
		},
		"job.salariu"
	},

	  
--===============[ JOBURI NOI ~ FINISH]===============--
--Groove--------------------------------
	["Lider Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiafull.arme",
		"mafiot.chat",
		"lider.salar"
	},
	["Co-Lider Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiafull.arme",
		"mafiot.chat",
		"colider.salar"
	},
	["Interlop Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiot.chat",
		"interlop.salar"
	},
	["Camatar Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiot.chat",
		"camatar.salar"
	},
	["Membru Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiot.chat",
		"membru.salar"
	},
	["Sageata Groove Street"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"grove.masini",
		"mafiot.chat",
		"sageata.salar"
	},
---Crips-------------------------------------
["Lider Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiafull.arme",
	"mafiot.chat",
	"lider.salar"
},
["Co-Lider Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiafull.arme",
	"mafiot.chat",
	"colider.salar"
},
["Interlop Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiot.chat",
	"interlop.salar"
},
["Camatar Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiot.chat",
	"camatar.salar"
},
["Membru Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiot.chat",
	"membru.salar"
},
["Sageata Crips"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"crip.masini",
	"mafiot.chat",
	"sageata.salar"
},
---Casa de Papel----------------------------------
["Lider Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiafull.arme",
	"mafiot.chat",
	"lider.salar"
},
["Co-Lider Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiafull.arme",
	"mafiot.chat",
	"colider.salar"
},
["Interlop Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiot.chat",
	"interlop.salar"
},
["Camatar Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiot.chat",
	"camatar.salar"
},
["Membru Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiot.chat",
	"membru.salar"
},
["Sageata Casa De Papel"] = {
	"police.putinveh",
	"police.easy_cuff",
	"police.getoutveh",
	"police.drag",
	"police.menu",
	"casa.masini",
	"mafiot.chat",
	"sageata.salar"
},
------------------------------------------	
	["Co-Lider Mecanici"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"mecanic.acces",
		"sniper.acces",
		"mafiot.chat"
	},	
	["Mecanic"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
        "mecanic.acces",
		"sniper.acces",
		"mafiot.chat"
	},
	["Lider Sinaloa Cartel"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"sinaloa.masini",
		"sinaloal.masini",
		"mafia.arme",
		"mafiot.chat"
	},
	["Co-Lider Sinaloa Cartel"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"sinaloa.masini",
		"sinaloal.masini",
		"mafia.arme",
		"mafiot.chat"
	},		
	["Sinaloa Cartel"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
		"vanzator.droguri",
		"mafiot.chat",
        "police.menu",
        "sinaloa.masini",
        "mafia.arme"
	},
	["Lider Peaky Blinders"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
		"police.menu",
		"mafiot.chat",
		"peaky.masini",
		"peakyl.masini",
        "mafia.arme"
	},	
	["Co-Lider Peaky Blinders"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"peaky.masini",
		"mafiot.chat",
		"peakyl.masini",
        "mafia.arme"
	},	
	["Peaky Blinders"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
		"vanzator.droguri",
		"mafiot.chat",
        "police.menu",
        "peaky.masini",
        "mafia.arme"
	},		
	["Lider Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
		"police.menu",
		"mafiot.chat",
        "curcubeu.masini",
        "mafia.arme"
	},		
	["Co-Lider Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
		"vanzator.droguri",
		"mafiot.chat",
        "police.menu",
        "curcubeu.masini",
        "mafia.arme"
	},
	["Curcubeu"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
		"vanzator.droguri",
		"mafiot.chat",
        "police.menu",
        "curcubeu.masini",
        "mafia.arme"
	},	
	["Lider LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"vagos.masini",
		"mafiot.chat",
		"sniper.acces",
		"vagos.salariu"
	},		
	["Co-Lider LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
		"police.menu",
		"mafiot.chat",
        "vagos.masini",
		"vagos.salariu",
		"sniper.acces"
	},
	["LosVagos"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "vanzator.droguri",
        "police.menu",
		"vagos.masini",
		"mafiot.chat",
		"sniper.acces",
		"vagos.salariu"
	},
	["Lider Bloodz"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "gang.acces",
		"gang.chat"
	},		
	["Co-Lider Bloodz"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "gang.acces",
		"gang.chat"
	},
	["Bloodz"] = {
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
        "police.drag",
        "police.menu",
		"gang.acces",
		"gang.chat"
	},
	  ["SONS OF ANARCHY"] = {
		"scu.cloakroom",
		"police.putinveh",
		"police.easy_cuff",
        "police.getoutveh",
		"police.drag",
		"mafiot.chat",
        "vanzator.droguri",
        "police.menu",
        "scu.masini",
		"sniper.acces",
        "scu.skin"		
	},	
	["Co-Lider SONS OF ANARCHY"] = {
		"scu.cloakroom",
        "police.putinveh",
		"police.getoutveh",
		"mafiot.chat",
        "police.drag",
		"sniper.acces",
        "vanzator.droguri",
		"police.menu",
		"police.easy_cuff",
        "scu.masini",
        "scu.skin"	
	},	
	["Lider SONS OF ANARCHY"] = {
		"scu.cloakroom",
		"police.putinveh",
		"police.easy_cuff",
		"mafiot.chat",
        "police.getoutveh",
        "police.drag",
		"sniper.acces",
        "vanzator.droguri",
        "police.menu",
        "scu.masini",
        "scu.skin"	
	}	  
}
-- GRUPE ID 1
cfg.users = {
  [1] = { -- II DA OWNER-ULUI URMATOARELE GRADE:
		"superadmin",
		"dev",
		"Community Manager",
		"recruiter",
  }
}

-- GRUPE DE LUAT
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["Agentia Fortelor de Munca"] = {
    _config = {x = -1083.0966796875, y = -248.15505981445, z = 37.763290405273},
	--"Ciresar",
	--"Fermier",	
    "Somer"
  },
  ["Agentia Fortelor de Munca #2"] = { 
    _config = {x = -1081.3146972656, y = -247.17333984375, z = 37.763278961182, permissions = {"amjoburipeserver.inpulamea"} },
    "Somer"
  }


  --[[["Hitman"] = {
    _config = {x = -1911.9273681641, y = -569.71649169922, z = 19.097215652466, blipid = 351, blipcolor = 7, permissions = {"jobhitman.acces"} },
    "Hitman",
	"Somer"
  },
  ["Judge"] = {
    _config = {x = -59.127178192139, y = 359.25082397461, z = 113.05643463135, blipid = 351, blipcolor = 7, permissions = {"Judge.whitelisted"} },
    "Judge",
	"Somer"
  },]]


}

return cfg
